<?xml version="1.0"?>

<!--
	definitions of some macros for easier description of the robot
-->

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  
   <xacro:macro name="cylinder_inertia" params="m r h">

    <inertia  
          ixx="${m*(3*r*r+h*h)/12}" 
    			ixy = "0" 
    			ixz = "0"
    			iyy="${m*(3*r*r+h*h)/12}" 
    			iyz = "0"
    			izz="${m*r*r/2}"
    />
  </xacro:macro>

  <xacro:macro name="box_inertia" params="m x y z">
    <inertia  
          ixx="${m*(y*y+z*z)/12}" 
    			ixy = "0" 
    			ixz = "0"
    			iyy="${m*(x*x+z*z)/12}" 
    			iyz = "0"
    			izz="${m*(x*x+z*z)/12}"
    />
  </xacro:macro>

  <xacro:macro name="sphere_inertia" params="m r">
    <inertia  
          ixx="${2*m*r*r/5}" 
    			ixy = "0" 
    			ixz = "0"
    			iyy="${2*m*r*r/5}" 
    			iyz = "0"
    			izz="${2*m*r*r/5}"
    />
  </xacro:macro>

  <xacro:macro name="wheel" params="lr tY">

    <link name="${lr}_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
        <geometry>
        	<cylinder length="${wheelWidthforCollision}"  radius="${wheelRadius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
        <geometry>
			<cylinder radius="${wheelRadius}" length = "${wheelWidth}"/>
        </geometry>
		<material name="DarkGray" />
      </visual>

      <inertial>
        <origin xyz="0 0 0" />
        <mass value="${wheelMass}"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
      </inertial>
    </link>

    <gazebo reference="${lr}_wheel"> 
      <mu1 value="100"/>
      <mu2 value="100"/>
      <!-- <mu1 value="2.0"/>
      <mu2 value="2.0"/> -->
      <kp  value="10000000.0" />
      
      <kd>100.0</kd>
      <minDepth>0.001</minDepth>
      <!-- <maxVel>1.0</maxVel> -->
      <material>Gazebo/FlatBlack</material>
    </gazebo>


    <joint name="${lr}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${lr}_wheel"/>
      <origin 
        xyz = "0 ${tY*(-wheelOffsetY)} ${wheelOffsetZ}"   rpy = "0 0 0" /> 
      <axis xyz="0 1 0"  rpy="0 0 0" />
    </joint>


    <transmission name="${lr}_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${lr}_wheel_joint">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
      <actuator name="${lr}Motor">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>-->
        </actuator>
    </transmission>

  </xacro:macro>

</robot>